// Generated by scripts/build-tokens.mjs from tokens/tokens.json — do not edit.

export const colors = {
  light: {
    "canvas": "#f4f3ef",
    "wash": "rgba(17, 17, 17, 0.06)",
    "skeleton": "rgba(17, 17, 17, 0.07)",
    "overlay": "rgba(17, 17, 17, 0.40)",
    "inverse": "#171717",
    "ink": "#111111",
    "muted": "#666666",
    "on-ink": "#f4f3ef",
    "accent": "#c8ff3d",
    "on-accent": "#111111",
    "accent-text": "#111111",
    "line": "rgba(17, 17, 17, 0.12)",
    "line-strong": "rgba(17, 17, 17, 0.24)",
    "focus": "#111111",
    "success": "#2d6a3e",
    "success-soft": "#dfe8d8",
    "warning": "#8a5300",
    "warning-soft": "#f2e3c2",
    "danger": "#a3301e",
    "danger-soft": "#f3dad3",
    "info": "#2e4d78",
    "info-soft": "#dce2ea"
  },
  dark: {
    "canvas": "#171717",
    "wash": "rgba(244, 243, 239, 0.08)",
    "skeleton": "rgba(244, 243, 239, 0.10)",
    "overlay": "rgba(0, 0, 0, 0.60)",
    "inverse": "#f4f3ef",
    "ink": "#f4f3ef",
    "muted": "#a3a29e",
    "on-ink": "#111111",
    "accent": "#c8ff3d",
    "on-accent": "#111111",
    "accent-text": "#c8ff3d",
    "line": "rgba(244, 243, 239, 0.16)",
    "line-strong": "rgba(244, 243, 239, 0.40)",
    "focus": "#c8ff3d",
    "success": "#8fd19e",
    "success-soft": "#28312a",
    "warning": "#f0c36b",
    "warning-soft": "#352f23",
    "danger": "#f29a86",
    "danger-soft": "#362926",
    "info": "#9db8e0",
    "info-soft": "#2a2e33"
  },
} as const;

export const radius = {"xs":6,"sm":8,"md":10,"lg":14,"full":9999} as const;

export const motion = {"easing":"cubic-bezier(0.16, 1, 0.3, 1)","fast":"150ms","base":"200ms","slow":"350ms","reveal":"700ms"} as const;

export type ColorToken = keyof typeof colors.light;
